### ISSUE TITLE
Add tasks

### ISSUE THREAD

**Issue by liki-mc** [ilovetocode2019/telegram.py#20]
## Summary
A way to add tasks in the bot. 
## The problem
When running asyncio functions, I keep getting a RuntimeError; in discord.py I could resolve it making use of tasks.
## The Ideal Solution
Having a similar syntax to the discord.ext.tasks module in discord.py to create extra tasks.

**Comment by ilovetocode2019** [comment]
Hi, `discord.ext.tasks` is just a thin wrapper for the asyncio task system. Because of this, you can actually use `discord.ext.tasks` with this library just as you would in a discord bot. In fact, you can really use it for anything involving asyncio. You can also implement it yourself if you'd rather, in a few lines of code using `asyncio.create_task`, a loop, and `asyncio.sleep`.

Additionally, you seem to be getting an unexpected `RuntimeError`, so it would be helpful if you could clarify the error. A code example/snippet and the `python -version` output would be appreciated.

**Comment by liki-mc** [comment]
Hi, thank you for responding so quickly. <br/>
I'll check out the tutorial, seems like a real fun one go through. Sorry to bother you.

**Comment by ilovetocode2019** [comment]
No worries :)

I'm glad I was able to help you.
